language: node_js
node_js:
  - "0.10"
before_install: cd DevCommunity
install: npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm test
after_success: cat TestResults/coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js