language: node_js
node_js:
  - "0.10"
before_install: cd DevCommunity
install: 
  - npm install -g grunt-cli
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: 
  - grunt build
  - npm test
after_success: cat TestResults/Client/coverage/*/lcov.info TestResults/Server/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js